<?php
$site = $this->vars('site');
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);

//gestion des identifiants de style Muse
$stylePageNavig = [
    "Présentation du projet"=>"u4713",
    "Protocole"=>"u4714",
    "Répondre à l'enquête"=>"u4715",
    "Exploration des résultats"=>"u4717",
    "Crédits de la recherche"=>"u4716"
]
?>

<div class="clearfix colelem" id="u3965"><!-- group -->
    <?php foreach($container as $page): ?>
        <a id="<?php echo $stylePageNavig[$page->label];?>-4"
        class="nonblock nontext clearfix grpelem
        <?php if($activePage && $page->label == $activePage['page']->label) echo 'MuseLinkActive';?>"  
        href="<?php echo $page->getHref(); ?>">
        <!-- content --><p><span id="<?php echo $stylePageNavig[$page->label];?>" ><?php echo $page->label; ?></span></p>
        </a>
    <?php endforeach; ?>
</div>



