<?php
error_reporting(E_ERROR | E_WARNING | E_PARSE);
$type = $this->params()->fromQuery('type','');
$log = $this->logger();

switch ($type) {
    case 'savePosi':
    case 'getPosis':
        $user = $this->identity();
        $posi = $this->CartoAffectFactory(['user'=>$user,'post'=>$this->params()->fromPost(),'query'=>$this->params()->fromQuery()]);
        echo $this->json($posi);                
    break;
    case 'getAnalyses':
        echo $this->json($this->getAnalyses(false,true));
    break;
}


?>



