<?php
$json = $this->params()->fromQuery('json') ? $this->params()->fromQuery('json') : $this->params()->fromPost('json', '');
if($json){
    echo $this->content;
    return ;
}

$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));

$this->headLink()->appendStylesheet($this->assetUrl('css/site_global.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/master_master_home.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/index.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/master_master_protocole.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/protocole.css'));


echo $this->doctype(); 
?>
<html class="nojs html css_verticalspacer" lang="en-US">
 <head>
        <?php echo $this->headTitle(); ?>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2015.2.0.352"/>
  
  <script type="text/javascript">
   // Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":[
    "jquery-1.8.3.min.js", 
    "museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "index.css"], "outOfDate":[]};
</script>
  
  <!-- CSS -->
  <?php echo $this->headLink(); ?>

   </head>
 <body>

  <div class="clearfix" id="page"><!-- column -->
   <div class="position_content" id="page_position_content">
    <div class="clearfix colelem" id="u3529"><!-- group -->
     <div class="clearfix grpelem" id="ppu3528-6"><!-- column -->
      <div class="clearfix colelem" id="pu3528-6"><!-- group -->
       <div class="clearfix grpelem" id="u3528-6"><!-- content -->
        <p id="u3528-2">Feuillet numérique - Enquête</p>
        <p id="u3528-4">Médiation numérique et éditorialisation des institutions théâtrales</p>
       </div>
       <div class="clip_frame grpelem" id="u3526"><!-- image -->
        <img class="block" id="u3526_img" src="<?php echo $this->assetUrl('images/logoparagraphe.jpg');?>" alt="" width="111" height="38"/>
       </div>
       <div class="clip_frame grpelem" id="u3531"><!-- image -->
        <img class="block" id="u3531_img" src="<?php echo $this->assetUrl('images/logop8.jpg');?>" alt="" width="76" height="38"/>
       </div>
      </div>
      <div class="clearfix colelem" id="u3530-6"><!-- content -->
       <p>Un projet de recherche doctoral de Gabrielle Godin (U. Laval et U. Paris 8 Vincennes-Saint-Denis)</p>
       <p>Dirigé par Renée Bourassa (U. Laval), Imad Saleh (U. Paris 8 Vincennes-Saint-Denis) et co-dirigé par Samuel Szoniecky (U. Paris 8 Vincennes-Saint-Denis)</p>
      </div>
     </div>
     <div class="clip_frame grpelem" id="u3524"><!-- image -->
      <img class="block" id="u3524_img" src="<?php echo $this->assetUrl('images/logo-ulaval-reseaux-sociaux.jpg');?>" alt="" width="74" height="39"/>
     </div>
    </div>
    <a class="nonblock nontext MuseLinkActive clearfix colelem" id="u3533-4" href="index.html"><!-- content --><p><span id="u3533">Évaluer le pouvoir d'agir par des cribles</span></p></a>
    <div class="clearfix colelem" id="u3523"><!-- column -->
     <div class="position_content" id="u3523_position_content">
        <?php echo $this->partial('FeuilletNumerique/navigation', ['site'=>$site]); ?>

        <?php echo $this->content; ?>

     </div>
    </div>
    <div class="verticalspacer" data-offset-top="0" data-content-above-spacer="1005" data-content-below-spacer="36"></div>
   </div>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   window.Muse.assets.check=function(){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var a={},b=function(){$('link[type="text/css"]').each(function(){var b=($(this).attr("href")||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);b&&b[1]&&b[2]&&(a[b[1]]=b[2])})},c=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),16);return 0},d=function(d){if("undefined"!==
typeof $){b();$("body").append('<div class="version" style="display:none; width:1px; height:1px;"></div>');for(var f=$(".version"),j=0;j<Muse.assets.required.length;){var h=Muse.assets.required[j],i=h.match(/([\w\-\.]+)\.(\w+)$/),k=i&&i[1]?i[1]:null,i=i&&i[2]?i[2]:null;switch(i.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");f.addClass(k);var i=c(f.css("color")),l=c(f.css("background-color"));i!=0||l!=0?(Muse.assets.required.splice(j,1),"undefined"!=typeof a[h]&&(i!=
a[h]>>>24||l!=(a[h]&16777215))&&Muse.assets.outOfDate.push(h)):j++;f.removeClass(k);break;case "js":k.match(/^jquery-[\d\.]+/gi)&&typeof $!="undefined"?Muse.assets.required.splice(j,1):j++;break;default:throw Error("Unsupported file type: "+i);}}f.remove()}if(Muse.assets.outOfDate.length||Muse.assets.required.length)f="Certains fichiers sur le serveur sont peut-être manquants ou incorrects. Videz le cache du navigateur et réessayez. Si le problème persiste, contactez le créateur du site.",d&&Muse.assets.outOfDate.length&&(f+="\nOut of date: "+Muse.assets.outOfDate.join(",")),d&&Muse.assets.required.length&&(f+="\nMissing: "+Muse.assets.required.join(",")),
alert(f)};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?setTimeout(function(){d(!0)},5E3):d()}};
var muse_init=function(){require.config({baseUrl:""});require(["museutils","whatinput","jquery.watch"],function(){$(document).ready(function(){try{
window.Muse.assets.check();/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.fullPage('#page');/* 100% height page */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(a){if(a&&"function"==typeof a.notify?a.notify():Muse.Assert.fail("Error calling selector function: "+a),false)throw a;}})})};

</script>
  <!-- RequireJS script -->  
  <script src="<?php echo $this->assetUrl('scripts/require.js');?>" type="text/javascript" async 
    data-main="<?php echo $this->assetUrl('scripts/museconfig.js');?>" 
    onload="requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>


